### ISSUE TITLE
Rename to gds-monitoring-plugins?

### ISSUE THREAD

**Issue by samjsharpe** [alphagov/nagios-plugins#3]
Given that these plugins aren't necessarily just for Nagios and noting that the nagios-plugins.org team have just undergone a [similar name change](https://www.monitoring-plugins.org/archive/devel/2014-January/009417.html), I suggest we rename this project to gds-monitoring-plugins.

**Comment by deanwilson** [comment]
We're slowly moving away from the existing monitoring over to a prometheus based world so this work will probably never happen due to the cost vs benefit. We're much more likely to archive the repo.

Thank you for raising it (many moons ago)
